// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/editorpost/spider/store/ent/extractindex"
	"github.com/google/uuid"
)

// ExtractIndexCreate is the builder for creating a ExtractIndex entity.
type ExtractIndexCreate struct {
	config
	mutation *ExtractIndexMutation
	hooks    []Hook
}

// SetPayloadID sets the "payload_id" field.
func (eic *ExtractIndexCreate) SetPayloadID(u uuid.UUID) *ExtractIndexCreate {
	eic.mutation.SetPayloadID(u)
	return eic
}

// SetSpiderID sets the "spider_id" field.
func (eic *ExtractIndexCreate) SetSpiderID(u uuid.UUID) *ExtractIndexCreate {
	eic.mutation.SetSpiderID(u)
	return eic
}

// SetTitle sets the "title" field.
func (eic *ExtractIndexCreate) SetTitle(s string) *ExtractIndexCreate {
	eic.mutation.SetTitle(s)
	return eic
}

// SetExtractedAt sets the "extracted_at" field.
func (eic *ExtractIndexCreate) SetExtractedAt(t time.Time) *ExtractIndexCreate {
	eic.mutation.SetExtractedAt(t)
	return eic
}

// SetNillableExtractedAt sets the "extracted_at" field if the given value is not nil.
func (eic *ExtractIndexCreate) SetNillableExtractedAt(t *time.Time) *ExtractIndexCreate {
	if t != nil {
		eic.SetExtractedAt(*t)
	}
	return eic
}

// SetStatus sets the "status" field.
func (eic *ExtractIndexCreate) SetStatus(u uint8) *ExtractIndexCreate {
	eic.mutation.SetStatus(u)
	return eic
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (eic *ExtractIndexCreate) SetNillableStatus(u *uint8) *ExtractIndexCreate {
	if u != nil {
		eic.SetStatus(*u)
	}
	return eic
}

// SetID sets the "id" field.
func (eic *ExtractIndexCreate) SetID(u uuid.UUID) *ExtractIndexCreate {
	eic.mutation.SetID(u)
	return eic
}

// SetNillableID sets the "id" field if the given value is not nil.
func (eic *ExtractIndexCreate) SetNillableID(u *uuid.UUID) *ExtractIndexCreate {
	if u != nil {
		eic.SetID(*u)
	}
	return eic
}

// Mutation returns the ExtractIndexMutation object of the builder.
func (eic *ExtractIndexCreate) Mutation() *ExtractIndexMutation {
	return eic.mutation
}

// Save creates the ExtractIndex in the database.
func (eic *ExtractIndexCreate) Save(ctx context.Context) (*ExtractIndex, error) {
	eic.defaults()
	return withHooks(ctx, eic.sqlSave, eic.mutation, eic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (eic *ExtractIndexCreate) SaveX(ctx context.Context) *ExtractIndex {
	v, err := eic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (eic *ExtractIndexCreate) Exec(ctx context.Context) error {
	_, err := eic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eic *ExtractIndexCreate) ExecX(ctx context.Context) {
	if err := eic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (eic *ExtractIndexCreate) defaults() {
	if _, ok := eic.mutation.ExtractedAt(); !ok {
		v := extractindex.DefaultExtractedAt()
		eic.mutation.SetExtractedAt(v)
	}
	if _, ok := eic.mutation.Status(); !ok {
		v := extractindex.DefaultStatus
		eic.mutation.SetStatus(v)
	}
	if _, ok := eic.mutation.ID(); !ok {
		v := extractindex.DefaultID()
		eic.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eic *ExtractIndexCreate) check() error {
	if _, ok := eic.mutation.PayloadID(); !ok {
		return &ValidationError{Name: "payload_id", err: errors.New(`ent: missing required field "ExtractIndex.payload_id"`)}
	}
	if _, ok := eic.mutation.SpiderID(); !ok {
		return &ValidationError{Name: "spider_id", err: errors.New(`ent: missing required field "ExtractIndex.spider_id"`)}
	}
	if _, ok := eic.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "ExtractIndex.title"`)}
	}
	if _, ok := eic.mutation.ExtractedAt(); !ok {
		return &ValidationError{Name: "extracted_at", err: errors.New(`ent: missing required field "ExtractIndex.extracted_at"`)}
	}
	if _, ok := eic.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ExtractIndex.status"`)}
	}
	return nil
}

func (eic *ExtractIndexCreate) sqlSave(ctx context.Context) (*ExtractIndex, error) {
	if err := eic.check(); err != nil {
		return nil, err
	}
	_node, _spec := eic.createSpec()
	if err := sqlgraph.CreateNode(ctx, eic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	eic.mutation.id = &_node.ID
	eic.mutation.done = true
	return _node, nil
}

func (eic *ExtractIndexCreate) createSpec() (*ExtractIndex, *sqlgraph.CreateSpec) {
	var (
		_node = &ExtractIndex{config: eic.config}
		_spec = sqlgraph.NewCreateSpec(extractindex.Table, sqlgraph.NewFieldSpec(extractindex.FieldID, field.TypeUUID))
	)
	if id, ok := eic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := eic.mutation.PayloadID(); ok {
		_spec.SetField(extractindex.FieldPayloadID, field.TypeUUID, value)
		_node.PayloadID = value
	}
	if value, ok := eic.mutation.SpiderID(); ok {
		_spec.SetField(extractindex.FieldSpiderID, field.TypeUUID, value)
		_node.SpiderID = value
	}
	if value, ok := eic.mutation.Title(); ok {
		_spec.SetField(extractindex.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := eic.mutation.ExtractedAt(); ok {
		_spec.SetField(extractindex.FieldExtractedAt, field.TypeTime, value)
		_node.ExtractedAt = value
	}
	if value, ok := eic.mutation.Status(); ok {
		_spec.SetField(extractindex.FieldStatus, field.TypeUint8, value)
		_node.Status = value
	}
	return _node, _spec
}

// ExtractIndexCreateBulk is the builder for creating many ExtractIndex entities in bulk.
type ExtractIndexCreateBulk struct {
	config
	err      error
	builders []*ExtractIndexCreate
}

// Save creates the ExtractIndex entities in the database.
func (eicb *ExtractIndexCreateBulk) Save(ctx context.Context) ([]*ExtractIndex, error) {
	if eicb.err != nil {
		return nil, eicb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(eicb.builders))
	nodes := make([]*ExtractIndex, len(eicb.builders))
	mutators := make([]Mutator, len(eicb.builders))
	for i := range eicb.builders {
		func(i int, root context.Context) {
			builder := eicb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExtractIndexMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, eicb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, eicb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, eicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (eicb *ExtractIndexCreateBulk) SaveX(ctx context.Context) []*ExtractIndex {
	v, err := eicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (eicb *ExtractIndexCreateBulk) Exec(ctx context.Context) error {
	_, err := eicb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eicb *ExtractIndexCreateBulk) ExecX(ctx context.Context) {
	if err := eicb.Exec(ctx); err != nil {
		panic(err)
	}
}
