// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/editorpost/spider/store/ent/extractindex"
	"github.com/editorpost/spider/store/ent/predicate"
	"github.com/google/uuid"
)

// ExtractIndexUpdate is the builder for updating ExtractIndex entities.
type ExtractIndexUpdate struct {
	config
	hooks    []Hook
	mutation *ExtractIndexMutation
}

// Where appends a list predicates to the ExtractIndexUpdate builder.
func (eiu *ExtractIndexUpdate) Where(ps ...predicate.ExtractIndex) *ExtractIndexUpdate {
	eiu.mutation.Where(ps...)
	return eiu
}

// SetSpiderID sets the "spider_id" field.
func (eiu *ExtractIndexUpdate) SetSpiderID(u uuid.UUID) *ExtractIndexUpdate {
	eiu.mutation.SetSpiderID(u)
	return eiu
}

// SetNillableSpiderID sets the "spider_id" field if the given value is not nil.
func (eiu *ExtractIndexUpdate) SetNillableSpiderID(u *uuid.UUID) *ExtractIndexUpdate {
	if u != nil {
		eiu.SetSpiderID(*u)
	}
	return eiu
}

// SetPayloadID sets the "payload_id" field.
func (eiu *ExtractIndexUpdate) SetPayloadID(s string) *ExtractIndexUpdate {
	eiu.mutation.SetPayloadID(s)
	return eiu
}

// SetNillablePayloadID sets the "payload_id" field if the given value is not nil.
func (eiu *ExtractIndexUpdate) SetNillablePayloadID(s *string) *ExtractIndexUpdate {
	if s != nil {
		eiu.SetPayloadID(*s)
	}
	return eiu
}

// SetExtractedAt sets the "extracted_at" field.
func (eiu *ExtractIndexUpdate) SetExtractedAt(t time.Time) *ExtractIndexUpdate {
	eiu.mutation.SetExtractedAt(t)
	return eiu
}

// SetNillableExtractedAt sets the "extracted_at" field if the given value is not nil.
func (eiu *ExtractIndexUpdate) SetNillableExtractedAt(t *time.Time) *ExtractIndexUpdate {
	if t != nil {
		eiu.SetExtractedAt(*t)
	}
	return eiu
}

// SetStatus sets the "status" field.
func (eiu *ExtractIndexUpdate) SetStatus(u uint8) *ExtractIndexUpdate {
	eiu.mutation.ResetStatus()
	eiu.mutation.SetStatus(u)
	return eiu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (eiu *ExtractIndexUpdate) SetNillableStatus(u *uint8) *ExtractIndexUpdate {
	if u != nil {
		eiu.SetStatus(*u)
	}
	return eiu
}

// AddStatus adds u to the "status" field.
func (eiu *ExtractIndexUpdate) AddStatus(u int8) *ExtractIndexUpdate {
	eiu.mutation.AddStatus(u)
	return eiu
}

// SetTitle sets the "title" field.
func (eiu *ExtractIndexUpdate) SetTitle(s string) *ExtractIndexUpdate {
	eiu.mutation.SetTitle(s)
	return eiu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (eiu *ExtractIndexUpdate) SetNillableTitle(s *string) *ExtractIndexUpdate {
	if s != nil {
		eiu.SetTitle(*s)
	}
	return eiu
}

// Mutation returns the ExtractIndexMutation object of the builder.
func (eiu *ExtractIndexUpdate) Mutation() *ExtractIndexMutation {
	return eiu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eiu *ExtractIndexUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, eiu.sqlSave, eiu.mutation, eiu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eiu *ExtractIndexUpdate) SaveX(ctx context.Context) int {
	affected, err := eiu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eiu *ExtractIndexUpdate) Exec(ctx context.Context) error {
	_, err := eiu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eiu *ExtractIndexUpdate) ExecX(ctx context.Context) {
	if err := eiu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eiu *ExtractIndexUpdate) check() error {
	if v, ok := eiu.mutation.PayloadID(); ok {
		if err := extractindex.PayloadIDValidator(v); err != nil {
			return &ValidationError{Name: "payload_id", err: fmt.Errorf(`ent: validator failed for field "ExtractIndex.payload_id": %w`, err)}
		}
	}
	return nil
}

func (eiu *ExtractIndexUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := eiu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(extractindex.Table, extractindex.Columns, sqlgraph.NewFieldSpec(extractindex.FieldID, field.TypeUUID))
	if ps := eiu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eiu.mutation.SpiderID(); ok {
		_spec.SetField(extractindex.FieldSpiderID, field.TypeUUID, value)
	}
	if value, ok := eiu.mutation.PayloadID(); ok {
		_spec.SetField(extractindex.FieldPayloadID, field.TypeString, value)
	}
	if value, ok := eiu.mutation.ExtractedAt(); ok {
		_spec.SetField(extractindex.FieldExtractedAt, field.TypeTime, value)
	}
	if value, ok := eiu.mutation.Status(); ok {
		_spec.SetField(extractindex.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := eiu.mutation.AddedStatus(); ok {
		_spec.AddField(extractindex.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := eiu.mutation.Title(); ok {
		_spec.SetField(extractindex.FieldTitle, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eiu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{extractindex.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	eiu.mutation.done = true
	return n, nil
}

// ExtractIndexUpdateOne is the builder for updating a single ExtractIndex entity.
type ExtractIndexUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ExtractIndexMutation
}

// SetSpiderID sets the "spider_id" field.
func (eiuo *ExtractIndexUpdateOne) SetSpiderID(u uuid.UUID) *ExtractIndexUpdateOne {
	eiuo.mutation.SetSpiderID(u)
	return eiuo
}

// SetNillableSpiderID sets the "spider_id" field if the given value is not nil.
func (eiuo *ExtractIndexUpdateOne) SetNillableSpiderID(u *uuid.UUID) *ExtractIndexUpdateOne {
	if u != nil {
		eiuo.SetSpiderID(*u)
	}
	return eiuo
}

// SetPayloadID sets the "payload_id" field.
func (eiuo *ExtractIndexUpdateOne) SetPayloadID(s string) *ExtractIndexUpdateOne {
	eiuo.mutation.SetPayloadID(s)
	return eiuo
}

// SetNillablePayloadID sets the "payload_id" field if the given value is not nil.
func (eiuo *ExtractIndexUpdateOne) SetNillablePayloadID(s *string) *ExtractIndexUpdateOne {
	if s != nil {
		eiuo.SetPayloadID(*s)
	}
	return eiuo
}

// SetExtractedAt sets the "extracted_at" field.
func (eiuo *ExtractIndexUpdateOne) SetExtractedAt(t time.Time) *ExtractIndexUpdateOne {
	eiuo.mutation.SetExtractedAt(t)
	return eiuo
}

// SetNillableExtractedAt sets the "extracted_at" field if the given value is not nil.
func (eiuo *ExtractIndexUpdateOne) SetNillableExtractedAt(t *time.Time) *ExtractIndexUpdateOne {
	if t != nil {
		eiuo.SetExtractedAt(*t)
	}
	return eiuo
}

// SetStatus sets the "status" field.
func (eiuo *ExtractIndexUpdateOne) SetStatus(u uint8) *ExtractIndexUpdateOne {
	eiuo.mutation.ResetStatus()
	eiuo.mutation.SetStatus(u)
	return eiuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (eiuo *ExtractIndexUpdateOne) SetNillableStatus(u *uint8) *ExtractIndexUpdateOne {
	if u != nil {
		eiuo.SetStatus(*u)
	}
	return eiuo
}

// AddStatus adds u to the "status" field.
func (eiuo *ExtractIndexUpdateOne) AddStatus(u int8) *ExtractIndexUpdateOne {
	eiuo.mutation.AddStatus(u)
	return eiuo
}

// SetTitle sets the "title" field.
func (eiuo *ExtractIndexUpdateOne) SetTitle(s string) *ExtractIndexUpdateOne {
	eiuo.mutation.SetTitle(s)
	return eiuo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (eiuo *ExtractIndexUpdateOne) SetNillableTitle(s *string) *ExtractIndexUpdateOne {
	if s != nil {
		eiuo.SetTitle(*s)
	}
	return eiuo
}

// Mutation returns the ExtractIndexMutation object of the builder.
func (eiuo *ExtractIndexUpdateOne) Mutation() *ExtractIndexMutation {
	return eiuo.mutation
}

// Where appends a list predicates to the ExtractIndexUpdate builder.
func (eiuo *ExtractIndexUpdateOne) Where(ps ...predicate.ExtractIndex) *ExtractIndexUpdateOne {
	eiuo.mutation.Where(ps...)
	return eiuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (eiuo *ExtractIndexUpdateOne) Select(field string, fields ...string) *ExtractIndexUpdateOne {
	eiuo.fields = append([]string{field}, fields...)
	return eiuo
}

// Save executes the query and returns the updated ExtractIndex entity.
func (eiuo *ExtractIndexUpdateOne) Save(ctx context.Context) (*ExtractIndex, error) {
	return withHooks(ctx, eiuo.sqlSave, eiuo.mutation, eiuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eiuo *ExtractIndexUpdateOne) SaveX(ctx context.Context) *ExtractIndex {
	node, err := eiuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (eiuo *ExtractIndexUpdateOne) Exec(ctx context.Context) error {
	_, err := eiuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eiuo *ExtractIndexUpdateOne) ExecX(ctx context.Context) {
	if err := eiuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eiuo *ExtractIndexUpdateOne) check() error {
	if v, ok := eiuo.mutation.PayloadID(); ok {
		if err := extractindex.PayloadIDValidator(v); err != nil {
			return &ValidationError{Name: "payload_id", err: fmt.Errorf(`ent: validator failed for field "ExtractIndex.payload_id": %w`, err)}
		}
	}
	return nil
}

func (eiuo *ExtractIndexUpdateOne) sqlSave(ctx context.Context) (_node *ExtractIndex, err error) {
	if err := eiuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(extractindex.Table, extractindex.Columns, sqlgraph.NewFieldSpec(extractindex.FieldID, field.TypeUUID))
	id, ok := eiuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ExtractIndex.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := eiuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, extractindex.FieldID)
		for _, f := range fields {
			if !extractindex.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != extractindex.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := eiuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eiuo.mutation.SpiderID(); ok {
		_spec.SetField(extractindex.FieldSpiderID, field.TypeUUID, value)
	}
	if value, ok := eiuo.mutation.PayloadID(); ok {
		_spec.SetField(extractindex.FieldPayloadID, field.TypeString, value)
	}
	if value, ok := eiuo.mutation.ExtractedAt(); ok {
		_spec.SetField(extractindex.FieldExtractedAt, field.TypeTime, value)
	}
	if value, ok := eiuo.mutation.Status(); ok {
		_spec.SetField(extractindex.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := eiuo.mutation.AddedStatus(); ok {
		_spec.AddField(extractindex.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := eiuo.mutation.Title(); ok {
		_spec.SetField(extractindex.FieldTitle, field.TypeString, value)
	}
	_node = &ExtractIndex{config: eiuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, eiuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{extractindex.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	eiuo.mutation.done = true
	return _node, nil
}
