// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/editorpost/spider/store/ent/extractindex"
	"github.com/editorpost/spider/store/ent/predicate"
	"github.com/google/uuid"
)

// ExtractIndexQuery is the builder for querying ExtractIndex entities.
type ExtractIndexQuery struct {
	config
	ctx        *QueryContext
	order      []extractindex.OrderOption
	inters     []Interceptor
	predicates []predicate.ExtractIndex
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ExtractIndexQuery builder.
func (eiq *ExtractIndexQuery) Where(ps ...predicate.ExtractIndex) *ExtractIndexQuery {
	eiq.predicates = append(eiq.predicates, ps...)
	return eiq
}

// Limit the number of records to be returned by this query.
func (eiq *ExtractIndexQuery) Limit(limit int) *ExtractIndexQuery {
	eiq.ctx.Limit = &limit
	return eiq
}

// Offset to start from.
func (eiq *ExtractIndexQuery) Offset(offset int) *ExtractIndexQuery {
	eiq.ctx.Offset = &offset
	return eiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (eiq *ExtractIndexQuery) Unique(unique bool) *ExtractIndexQuery {
	eiq.ctx.Unique = &unique
	return eiq
}

// Order specifies how the records should be ordered.
func (eiq *ExtractIndexQuery) Order(o ...extractindex.OrderOption) *ExtractIndexQuery {
	eiq.order = append(eiq.order, o...)
	return eiq
}

// First returns the first ExtractIndex entity from the query.
// Returns a *NotFoundError when no ExtractIndex was found.
func (eiq *ExtractIndexQuery) First(ctx context.Context) (*ExtractIndex, error) {
	nodes, err := eiq.Limit(1).All(setContextOp(ctx, eiq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{extractindex.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (eiq *ExtractIndexQuery) FirstX(ctx context.Context) *ExtractIndex {
	node, err := eiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ExtractIndex ID from the query.
// Returns a *NotFoundError when no ExtractIndex ID was found.
func (eiq *ExtractIndexQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = eiq.Limit(1).IDs(setContextOp(ctx, eiq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{extractindex.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (eiq *ExtractIndexQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := eiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ExtractIndex entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ExtractIndex entity is found.
// Returns a *NotFoundError when no ExtractIndex entities are found.
func (eiq *ExtractIndexQuery) Only(ctx context.Context) (*ExtractIndex, error) {
	nodes, err := eiq.Limit(2).All(setContextOp(ctx, eiq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{extractindex.Label}
	default:
		return nil, &NotSingularError{extractindex.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (eiq *ExtractIndexQuery) OnlyX(ctx context.Context) *ExtractIndex {
	node, err := eiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ExtractIndex ID in the query.
// Returns a *NotSingularError when more than one ExtractIndex ID is found.
// Returns a *NotFoundError when no entities are found.
func (eiq *ExtractIndexQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = eiq.Limit(2).IDs(setContextOp(ctx, eiq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{extractindex.Label}
	default:
		err = &NotSingularError{extractindex.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (eiq *ExtractIndexQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := eiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ExtractIndexes.
func (eiq *ExtractIndexQuery) All(ctx context.Context) ([]*ExtractIndex, error) {
	ctx = setContextOp(ctx, eiq.ctx, "All")
	if err := eiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ExtractIndex, *ExtractIndexQuery]()
	return withInterceptors[[]*ExtractIndex](ctx, eiq, qr, eiq.inters)
}

// AllX is like All, but panics if an error occurs.
func (eiq *ExtractIndexQuery) AllX(ctx context.Context) []*ExtractIndex {
	nodes, err := eiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ExtractIndex IDs.
func (eiq *ExtractIndexQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if eiq.ctx.Unique == nil && eiq.path != nil {
		eiq.Unique(true)
	}
	ctx = setContextOp(ctx, eiq.ctx, "IDs")
	if err = eiq.Select(extractindex.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (eiq *ExtractIndexQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := eiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (eiq *ExtractIndexQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, eiq.ctx, "Count")
	if err := eiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, eiq, querierCount[*ExtractIndexQuery](), eiq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (eiq *ExtractIndexQuery) CountX(ctx context.Context) int {
	count, err := eiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (eiq *ExtractIndexQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, eiq.ctx, "Exist")
	switch _, err := eiq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (eiq *ExtractIndexQuery) ExistX(ctx context.Context) bool {
	exist, err := eiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ExtractIndexQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (eiq *ExtractIndexQuery) Clone() *ExtractIndexQuery {
	if eiq == nil {
		return nil
	}
	return &ExtractIndexQuery{
		config:     eiq.config,
		ctx:        eiq.ctx.Clone(),
		order:      append([]extractindex.OrderOption{}, eiq.order...),
		inters:     append([]Interceptor{}, eiq.inters...),
		predicates: append([]predicate.ExtractIndex{}, eiq.predicates...),
		// clone intermediate query.
		sql:  eiq.sql.Clone(),
		path: eiq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PayloadID uuid.UUID `json:"payload_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ExtractIndex.Query().
//		GroupBy(extractindex.FieldPayloadID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (eiq *ExtractIndexQuery) GroupBy(field string, fields ...string) *ExtractIndexGroupBy {
	eiq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ExtractIndexGroupBy{build: eiq}
	grbuild.flds = &eiq.ctx.Fields
	grbuild.label = extractindex.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PayloadID uuid.UUID `json:"payload_id,omitempty"`
//	}
//
//	client.ExtractIndex.Query().
//		Select(extractindex.FieldPayloadID).
//		Scan(ctx, &v)
func (eiq *ExtractIndexQuery) Select(fields ...string) *ExtractIndexSelect {
	eiq.ctx.Fields = append(eiq.ctx.Fields, fields...)
	sbuild := &ExtractIndexSelect{ExtractIndexQuery: eiq}
	sbuild.label = extractindex.Label
	sbuild.flds, sbuild.scan = &eiq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ExtractIndexSelect configured with the given aggregations.
func (eiq *ExtractIndexQuery) Aggregate(fns ...AggregateFunc) *ExtractIndexSelect {
	return eiq.Select().Aggregate(fns...)
}

func (eiq *ExtractIndexQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range eiq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, eiq); err != nil {
				return err
			}
		}
	}
	for _, f := range eiq.ctx.Fields {
		if !extractindex.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if eiq.path != nil {
		prev, err := eiq.path(ctx)
		if err != nil {
			return err
		}
		eiq.sql = prev
	}
	return nil
}

func (eiq *ExtractIndexQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ExtractIndex, error) {
	var (
		nodes = []*ExtractIndex{}
		_spec = eiq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ExtractIndex).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ExtractIndex{config: eiq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, eiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (eiq *ExtractIndexQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := eiq.querySpec()
	_spec.Node.Columns = eiq.ctx.Fields
	if len(eiq.ctx.Fields) > 0 {
		_spec.Unique = eiq.ctx.Unique != nil && *eiq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, eiq.driver, _spec)
}

func (eiq *ExtractIndexQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(extractindex.Table, extractindex.Columns, sqlgraph.NewFieldSpec(extractindex.FieldID, field.TypeUUID))
	_spec.From = eiq.sql
	if unique := eiq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if eiq.path != nil {
		_spec.Unique = true
	}
	if fields := eiq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, extractindex.FieldID)
		for i := range fields {
			if fields[i] != extractindex.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := eiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := eiq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := eiq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := eiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (eiq *ExtractIndexQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(eiq.driver.Dialect())
	t1 := builder.Table(extractindex.Table)
	columns := eiq.ctx.Fields
	if len(columns) == 0 {
		columns = extractindex.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if eiq.sql != nil {
		selector = eiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if eiq.ctx.Unique != nil && *eiq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range eiq.predicates {
		p(selector)
	}
	for _, p := range eiq.order {
		p(selector)
	}
	if offset := eiq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := eiq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ExtractIndexGroupBy is the group-by builder for ExtractIndex entities.
type ExtractIndexGroupBy struct {
	selector
	build *ExtractIndexQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (eigb *ExtractIndexGroupBy) Aggregate(fns ...AggregateFunc) *ExtractIndexGroupBy {
	eigb.fns = append(eigb.fns, fns...)
	return eigb
}

// Scan applies the selector query and scans the result into the given value.
func (eigb *ExtractIndexGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, eigb.build.ctx, "GroupBy")
	if err := eigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ExtractIndexQuery, *ExtractIndexGroupBy](ctx, eigb.build, eigb, eigb.build.inters, v)
}

func (eigb *ExtractIndexGroupBy) sqlScan(ctx context.Context, root *ExtractIndexQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(eigb.fns))
	for _, fn := range eigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*eigb.flds)+len(eigb.fns))
		for _, f := range *eigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*eigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := eigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ExtractIndexSelect is the builder for selecting fields of ExtractIndex entities.
type ExtractIndexSelect struct {
	*ExtractIndexQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (eis *ExtractIndexSelect) Aggregate(fns ...AggregateFunc) *ExtractIndexSelect {
	eis.fns = append(eis.fns, fns...)
	return eis
}

// Scan applies the selector query and scans the result into the given value.
func (eis *ExtractIndexSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, eis.ctx, "Select")
	if err := eis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ExtractIndexQuery, *ExtractIndexSelect](ctx, eis.ExtractIndexQuery, eis, eis.inters, v)
}

func (eis *ExtractIndexSelect) sqlScan(ctx context.Context, root *ExtractIndexQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(eis.fns))
	for _, fn := range eis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*eis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := eis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
