// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/editorpost/spider/store/ent/extractindex"
	"github.com/google/uuid"
)

// ExtractIndex is the model entity for the ExtractIndex schema.
type ExtractIndex struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// PayloadID holds the value of the "payload_id" field.
	PayloadID uuid.UUID `json:"payload_id,omitempty"`
	// SpiderID holds the value of the "spider_id" field.
	SpiderID uuid.UUID `json:"spider_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// ExtractedAt holds the value of the "extracted_at" field.
	ExtractedAt time.Time `json:"extracted_at,omitempty"`
	// Status holds the value of the "status" field.
	Status       uint8 `json:"status,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ExtractIndex) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case extractindex.FieldStatus:
			values[i] = new(sql.NullInt64)
		case extractindex.FieldTitle:
			values[i] = new(sql.NullString)
		case extractindex.FieldExtractedAt:
			values[i] = new(sql.NullTime)
		case extractindex.FieldID, extractindex.FieldPayloadID, extractindex.FieldSpiderID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ExtractIndex fields.
func (ei *ExtractIndex) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case extractindex.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ei.ID = *value
			}
		case extractindex.FieldPayloadID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field payload_id", values[i])
			} else if value != nil {
				ei.PayloadID = *value
			}
		case extractindex.FieldSpiderID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field spider_id", values[i])
			} else if value != nil {
				ei.SpiderID = *value
			}
		case extractindex.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				ei.Title = value.String
			}
		case extractindex.FieldExtractedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field extracted_at", values[i])
			} else if value.Valid {
				ei.ExtractedAt = value.Time
			}
		case extractindex.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				ei.Status = uint8(value.Int64)
			}
		default:
			ei.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ExtractIndex.
// This includes values selected through modifiers, order, etc.
func (ei *ExtractIndex) Value(name string) (ent.Value, error) {
	return ei.selectValues.Get(name)
}

// Update returns a builder for updating this ExtractIndex.
// Note that you need to call ExtractIndex.Unwrap() before calling this method if this ExtractIndex
// was returned from a transaction, and the transaction was committed or rolled back.
func (ei *ExtractIndex) Update() *ExtractIndexUpdateOne {
	return NewExtractIndexClient(ei.config).UpdateOne(ei)
}

// Unwrap unwraps the ExtractIndex entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ei *ExtractIndex) Unwrap() *ExtractIndex {
	_tx, ok := ei.config.driver.(*txDriver)
	if !ok {
		panic("ent: ExtractIndex is not a transactional entity")
	}
	ei.config.driver = _tx.drv
	return ei
}

// String implements the fmt.Stringer.
func (ei *ExtractIndex) String() string {
	var builder strings.Builder
	builder.WriteString("ExtractIndex(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ei.ID))
	builder.WriteString("payload_id=")
	builder.WriteString(fmt.Sprintf("%v", ei.PayloadID))
	builder.WriteString(", ")
	builder.WriteString("spider_id=")
	builder.WriteString(fmt.Sprintf("%v", ei.SpiderID))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(ei.Title)
	builder.WriteString(", ")
	builder.WriteString("extracted_at=")
	builder.WriteString(ei.ExtractedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", ei.Status))
	builder.WriteByte(')')
	return builder.String()
}

// ExtractIndexes is a parsable slice of ExtractIndex.
type ExtractIndexes []*ExtractIndex
