// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/editorpost/spider/store/ent/extractindex"
	"github.com/editorpost/spider/store/ent/predicate"
)

// ExtractIndexDelete is the builder for deleting a ExtractIndex entity.
type ExtractIndexDelete struct {
	config
	hooks    []Hook
	mutation *ExtractIndexMutation
}

// Where appends a list predicates to the ExtractIndexDelete builder.
func (eid *ExtractIndexDelete) Where(ps ...predicate.ExtractIndex) *ExtractIndexDelete {
	eid.mutation.Where(ps...)
	return eid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (eid *ExtractIndexDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, eid.sqlExec, eid.mutation, eid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (eid *ExtractIndexDelete) ExecX(ctx context.Context) int {
	n, err := eid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (eid *ExtractIndexDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(extractindex.Table, sqlgraph.NewFieldSpec(extractindex.FieldID, field.TypeUUID))
	if ps := eid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, eid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	eid.mutation.done = true
	return affected, err
}

// ExtractIndexDeleteOne is the builder for deleting a single ExtractIndex entity.
type ExtractIndexDeleteOne struct {
	eid *ExtractIndexDelete
}

// Where appends a list predicates to the ExtractIndexDelete builder.
func (eido *ExtractIndexDeleteOne) Where(ps ...predicate.ExtractIndex) *ExtractIndexDeleteOne {
	eido.eid.mutation.Where(ps...)
	return eido
}

// Exec executes the deletion query.
func (eido *ExtractIndexDeleteOne) Exec(ctx context.Context) error {
	n, err := eido.eid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{extractindex.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (eido *ExtractIndexDeleteOne) ExecX(ctx context.Context) {
	if err := eido.Exec(ctx); err != nil {
		panic(err)
	}
}
