// Code generated by ent, DO NOT EDIT.

package spiderpayload

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the spiderpayload type in the database.
	Label = "spider_payload"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSpiderID holds the string denoting the spider_id field in the database.
	FieldSpiderID = "spider_id"
	// FieldPayloadID holds the string denoting the payload_id field in the database.
	FieldPayloadID = "payload_id"
	// FieldExtractedAt holds the string denoting the extracted_at field in the database.
	FieldExtractedAt = "extracted_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// Table holds the table name of the spiderpayload in the database.
	Table = "spider_payloads"
)

// Columns holds all SQL columns for spiderpayload fields.
var Columns = []string{
	FieldID,
	FieldSpiderID,
	FieldPayloadID,
	FieldExtractedAt,
	FieldStatus,
	FieldTitle,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PayloadIDValidator is a validator for the "payload_id" field. It is called by the builders before save.
	PayloadIDValidator func(string) error
	// DefaultExtractedAt holds the default value on creation for the "extracted_at" field.
	DefaultExtractedAt func() time.Time
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus uint8
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the SpiderPayload queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySpiderID orders the results by the spider_id field.
func BySpiderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpiderID, opts...).ToFunc()
}

// ByPayloadID orders the results by the payload_id field.
func ByPayloadID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayloadID, opts...).ToFunc()
}

// ByExtractedAt orders the results by the extracted_at field.
func ByExtractedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExtractedAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}
