// Code generated by ent, DO NOT EDIT.

package spiderpayload

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/editorpost/spider/store/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldLTE(FieldID, id))
}

// SpiderID applies equality check predicate on the "spider_id" field. It's identical to SpiderIDEQ.
func SpiderID(v uuid.UUID) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldEQ(FieldSpiderID, v))
}

// PayloadID applies equality check predicate on the "payload_id" field. It's identical to PayloadIDEQ.
func PayloadID(v string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldEQ(FieldPayloadID, v))
}

// ExtractedAt applies equality check predicate on the "extracted_at" field. It's identical to ExtractedAtEQ.
func ExtractedAt(v time.Time) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldEQ(FieldExtractedAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v uint8) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldEQ(FieldStatus, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldEQ(FieldTitle, v))
}

// SpiderIDEQ applies the EQ predicate on the "spider_id" field.
func SpiderIDEQ(v uuid.UUID) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldEQ(FieldSpiderID, v))
}

// SpiderIDNEQ applies the NEQ predicate on the "spider_id" field.
func SpiderIDNEQ(v uuid.UUID) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldNEQ(FieldSpiderID, v))
}

// SpiderIDIn applies the In predicate on the "spider_id" field.
func SpiderIDIn(vs ...uuid.UUID) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldIn(FieldSpiderID, vs...))
}

// SpiderIDNotIn applies the NotIn predicate on the "spider_id" field.
func SpiderIDNotIn(vs ...uuid.UUID) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldNotIn(FieldSpiderID, vs...))
}

// SpiderIDGT applies the GT predicate on the "spider_id" field.
func SpiderIDGT(v uuid.UUID) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldGT(FieldSpiderID, v))
}

// SpiderIDGTE applies the GTE predicate on the "spider_id" field.
func SpiderIDGTE(v uuid.UUID) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldGTE(FieldSpiderID, v))
}

// SpiderIDLT applies the LT predicate on the "spider_id" field.
func SpiderIDLT(v uuid.UUID) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldLT(FieldSpiderID, v))
}

// SpiderIDLTE applies the LTE predicate on the "spider_id" field.
func SpiderIDLTE(v uuid.UUID) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldLTE(FieldSpiderID, v))
}

// PayloadIDEQ applies the EQ predicate on the "payload_id" field.
func PayloadIDEQ(v string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldEQ(FieldPayloadID, v))
}

// PayloadIDNEQ applies the NEQ predicate on the "payload_id" field.
func PayloadIDNEQ(v string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldNEQ(FieldPayloadID, v))
}

// PayloadIDIn applies the In predicate on the "payload_id" field.
func PayloadIDIn(vs ...string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldIn(FieldPayloadID, vs...))
}

// PayloadIDNotIn applies the NotIn predicate on the "payload_id" field.
func PayloadIDNotIn(vs ...string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldNotIn(FieldPayloadID, vs...))
}

// PayloadIDGT applies the GT predicate on the "payload_id" field.
func PayloadIDGT(v string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldGT(FieldPayloadID, v))
}

// PayloadIDGTE applies the GTE predicate on the "payload_id" field.
func PayloadIDGTE(v string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldGTE(FieldPayloadID, v))
}

// PayloadIDLT applies the LT predicate on the "payload_id" field.
func PayloadIDLT(v string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldLT(FieldPayloadID, v))
}

// PayloadIDLTE applies the LTE predicate on the "payload_id" field.
func PayloadIDLTE(v string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldLTE(FieldPayloadID, v))
}

// PayloadIDContains applies the Contains predicate on the "payload_id" field.
func PayloadIDContains(v string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldContains(FieldPayloadID, v))
}

// PayloadIDHasPrefix applies the HasPrefix predicate on the "payload_id" field.
func PayloadIDHasPrefix(v string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldHasPrefix(FieldPayloadID, v))
}

// PayloadIDHasSuffix applies the HasSuffix predicate on the "payload_id" field.
func PayloadIDHasSuffix(v string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldHasSuffix(FieldPayloadID, v))
}

// PayloadIDEqualFold applies the EqualFold predicate on the "payload_id" field.
func PayloadIDEqualFold(v string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldEqualFold(FieldPayloadID, v))
}

// PayloadIDContainsFold applies the ContainsFold predicate on the "payload_id" field.
func PayloadIDContainsFold(v string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldContainsFold(FieldPayloadID, v))
}

// ExtractedAtEQ applies the EQ predicate on the "extracted_at" field.
func ExtractedAtEQ(v time.Time) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldEQ(FieldExtractedAt, v))
}

// ExtractedAtNEQ applies the NEQ predicate on the "extracted_at" field.
func ExtractedAtNEQ(v time.Time) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldNEQ(FieldExtractedAt, v))
}

// ExtractedAtIn applies the In predicate on the "extracted_at" field.
func ExtractedAtIn(vs ...time.Time) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldIn(FieldExtractedAt, vs...))
}

// ExtractedAtNotIn applies the NotIn predicate on the "extracted_at" field.
func ExtractedAtNotIn(vs ...time.Time) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldNotIn(FieldExtractedAt, vs...))
}

// ExtractedAtGT applies the GT predicate on the "extracted_at" field.
func ExtractedAtGT(v time.Time) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldGT(FieldExtractedAt, v))
}

// ExtractedAtGTE applies the GTE predicate on the "extracted_at" field.
func ExtractedAtGTE(v time.Time) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldGTE(FieldExtractedAt, v))
}

// ExtractedAtLT applies the LT predicate on the "extracted_at" field.
func ExtractedAtLT(v time.Time) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldLT(FieldExtractedAt, v))
}

// ExtractedAtLTE applies the LTE predicate on the "extracted_at" field.
func ExtractedAtLTE(v time.Time) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldLTE(FieldExtractedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v uint8) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v uint8) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...uint8) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...uint8) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v uint8) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v uint8) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v uint8) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v uint8) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldLTE(FieldStatus, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.FieldContainsFold(FieldTitle, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SpiderPayload) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SpiderPayload) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SpiderPayload) predicate.SpiderPayload {
	return predicate.SpiderPayload(sql.NotPredicates(p))
}
