// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ExtractIndex is the predicate function for extractindex builders.
type ExtractIndex func(*sql.Selector)
