// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// SpiderPayload is the predicate function for spiderpayload builders.
type SpiderPayload func(*sql.Selector)
