// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SpiderPayloadsColumns holds the columns for the "spider_payloads" table.
	SpiderPayloadsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "spider_id", Type: field.TypeUUID},
		{Name: "payload_id", Type: field.TypeString},
		{Name: "extracted_at", Type: field.TypeTime},
		{Name: "url", Type: field.TypeString, Nullable: true},
		{Name: "path", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeUint8, Default: 1},
		{Name: "title", Type: field.TypeString},
		{Name: "job_provider", Type: field.TypeString, Nullable: true},
		{Name: "job_id", Type: field.TypeUUID, Nullable: true},
	}
	// SpiderPayloadsTable holds the schema information for the "spider_payloads" table.
	SpiderPayloadsTable = &schema.Table{
		Name:       "spider_payloads",
		Columns:    SpiderPayloadsColumns,
		PrimaryKey: []*schema.Column{SpiderPayloadsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "spiderpayload_spider_id_extracted_at",
				Unique:  true,
				Columns: []*schema.Column{SpiderPayloadsColumns[1], SpiderPayloadsColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SpiderPayloadsTable,
	}
)

func init() {
}
