# .github/workflows/release.yaml

on:
  push:
    tags:
      - 'v*'

env:
  GO_VERSION: "~1.22.4"
jobs:
  build-test:
    name: Package for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
          check-latest: true

      - name: Get actual Go version
        run: |
          go version
          echo "GO_VERSION=$(go version | sed 's#^.*go##;s# .*##')" >> $GITHUB_ENV

      - name: Create package for amd64
        env:
          CGO_ENABLED: "0"
        run: |
          go build -v -ldflags="-s -w" -o spider-linux-amd64

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: spider-linux-amd64
          path: spider-linux-amd64
